### ISSUE TITLE
NameError when using trying to use ResNet Encoder

### ISSUE THREAD

**Issue by Dstecher** [cogaplex-bts/bts#106]
Hi, thank you for sharing your code!

After running your code with DenseNet-161 in default settings first and then trying out different encoders for training, I have now reached ResNet-101 and ResNet-50. Both give me the same set of errors which is why I will stick to ResNet-101 now: 

> Traceback (most recent call last):
  File "bts_main.py", line 328, in <module>
    tf.app.run()
  File "/home/dominik/anaconda3/envs/bts/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "bts_main.py", line 321, in main
    train(params)
  File "bts_main.py", line 168, in train
    reuse_variables=reuse_variables, model_index=i, bn_training=False)
  File "/home/dominik/workspace/bts/tensorflow/bts.py", line 59, in __init__
    self.build_model(net_input=self.input_image, reuse=self.reuse_variables)
  File "/home/dominik/workspace/bts/tensorflow/bts.py", line 428, in build_model
    self.build_resnet101_bts(net_input=net_input, reuse=reuse)
  File "/home/dominik/workspace/bts/tensorflow/bts.py", line 367, in build_resnet101_bts
    dense_features, skips, endpoints = resnet_v1_101(net_input, global_pool=False, spatial_squeeze=False,
NameError: name 'resnet_v1_101' is not defined

I have then tried to import `from tensorflow.contrib.slim.nets import resnet_v1` and therefore later use `dense_features, skips, endpoints = resnet_v1.resnet_v1_101(net_input, global_pool=False, spatial_squeeze=False,
                                                                 is_training=self.is_training, reuse=reuse, scope='resnet101')`, but this sadly still does not allow me to then use a ResNet encoder only giving me:

> Traceback (most recent call last):
  File "bts_main.py", line 328, in <module>
    tf.app.run()
  File "/home/dominik/anaconda3/envs/bts/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "bts_main.py", line 321, in main
    train(params)
  File "bts_main.py", line 168, in train
    reuse_variables=reuse_variables, model_index=i, bn_training=False)
  File "/home/dominik/workspace/bts/tensorflow/bts.py", line 59, in __init__
    self.build_model(net_input=self.input_image, reuse=self.reuse_variables)
  File "/home/dominik/workspace/bts/tensorflow/bts.py", line 428, in build_model
    self.build_resnet101_bts(net_input=net_input, reuse=reuse)
  File "/home/dominik/workspace/bts/tensorflow/bts.py", line 368, in build_resnet101_bts
    is_training=self.is_training, reuse=reuse, scope='resnet101')
TypeError: resnet_v1_101() got an unexpected keyword argument 'spatial_squeeze'

Trying to then remove the `spatial_squeeze=False` argument only gives me the following ValueError:

> Traceback (most recent call last):
  File "bts_main.py", line 328, in <module>
    tf.app.run()
  File "/home/dominik/anaconda3/envs/bts/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "bts_main.py", line 321, in main
    train(params)
  File "bts_main.py", line 168, in train
    reuse_variables=reuse_variables, model_index=i, bn_training=False)
  File "/home/dominik/workspace/bts/tensorflow/bts.py", line 59, in __init__
    self.build_model(net_input=self.input_image, reuse=self.reuse_variables)
  File "/home/dominik/workspace/bts/tensorflow/bts.py", line 428, in build_model
    self.build_resnet101_bts(net_input=net_input, reuse=reuse)
  File "/home/dominik/workspace/bts/tensorflow/bts.py", line 368, in build_resnet101_bts
    is_training=self.is_training, reuse=reuse, scope='resnet101')
ValueError: not enough values to unpack (expected 3, got 2)

I am using the TensorFlow implementation with Python 3.6, TensorFlow 1.13.2 and CUDA 10.0 on my Ubuntu 20.04 system. All packages were installed in a new conda environment and DenseNet-161 as well as DenseNet-121 have worked well as encoders before (as said).

Has anyone encountered this problem as well or knows about that and has a fix? Training on a single Nvidia GeForce GTX 1080 takes quite long sadly which is why I would like to test the other encoders as well.
Any kind of help would be greatly appreciated!

**Comment by Dstecher** [comment]
Something I just recognized I forgot to mention:
The first attempted fix was to explicitly import the given resnet_v1.py from this repository. This however only resulted in the following error, which I have not been able to resolve yet as well:

> Traceback (most recent call last):
  File "bts_main.py", line 328, in <module>
    tf.app.run()
  File "/home/dominik/anaconda3/envs/bts/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "bts_main.py", line 321, in main
    train(params)
  File "bts_main.py", line 168, in train
    reuse_variables=reuse_variables, model_index=i, bn_training=False)
  File "/home/dominik/workspace/bts/tensorflow/bts.py", line 59, in __init__
    self.build_model(net_input=self.input_image, reuse=self.reuse_variables)
  File "/home/dominik/workspace/bts/tensorflow/bts.py", line 428, in build_model
    self.build_resnet101_bts(net_input=net_input, reuse=reuse)
  File "/home/dominik/workspace/bts/tensorflow/bts.py", line 368, in build_resnet101_bts
    is_training=self.is_training, reuse=reuse, scope='resnet101')
  File "/home/dominik/workspace/bts/tensorflow/resnet_v1.py", line 319, in resnet_v1_101
    reuse=reuse, scope=scope)
  File "/home/dominik/workspace/bts/tensorflow/resnet_v1.py", line 219, in resnet_v1
    net, skips = resnet_utils.stack_blocks_dense(net, blocks, skips, output_stride, store_non_strided_activations)
  File "/home/dominik/anaconda3/envs/bts/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
TypeError: stack_blocks_dense() got multiple values for argument 'outputs_collections'

Please let me know if you are aware of something I could try. Thank you in advance!

**Comment by Dstecher** [comment]
@cogaplex-bts Thank you very much for your response! I have now tried the PyTorch version with both ResNet encoders and both seem to work well! 
Sadly, I cannot really achieve the hoped for benefit in terms of training time as ResNet-101 takes longer and ResNet-50 would take about the same time to train as I needed for DenseNet-121 with TensorFlow.

Still thank you for the advice and taking a look into the TensorFlow issue I had. In case you are able to find something or need any more information please let me know!
