### ISSUE TITLE
TypeError: only integer scalar arrays can be converted to a scalar index

### ISSUE THREAD

**Issue by 1byxero** [cogaplex-bts/bts#75]
I was getting above error when doing `Prepare NYU Depth V2 test set` step.
After debugging

**Comment by 1byxero** [comment]
Also, I just tried this on node of university cluster and I did not need to make the change I mentioned in the above comment

**Comment by Samad08** [comment]
hey thanks for the help. You saved me some time !!!

**Comment by xuelimin** [comment]
thanks！

**Comment by LeoRainly** [comment]
thanks a lot

**Comment by xuelimin** [comment]
邮件已查收，我会尽快回复您！

**Comment by YuhsiHu** [comment]
Thanks a lot. This issue saved me some time!

**Comment by xuelimin** [comment]
邮件已查收，我会尽快回复您！

**Comment by 962858249** [comment]
> I was getting above error when doing `Prepare NYU Depth V2 test set` step. The error trace was as follows when executing the command `python extract_official_train_test_set_from_mat.py nyu_depth_v2_labeled.mat splits.mat ../../dataset/nyu_depth_v2/official_splits/`
> 
> ```
> Traceback (most recent call last):
>   File "extract_official_train_test_set_from_mat.py", line 87, in <module>
>     scenes = [u''.join(chr(c) for c in h5_file[obj_ref]) for obj_ref in h5_file['sceneTypes'][0]]
>   File "extract_official_train_test_set_from_mat.py", line 87, in <listcomp>
>     scenes = [u''.join(chr(c) for c in h5_file[obj_ref]) for obj_ref in h5_file['sceneTypes'][0]]
>   File "extract_official_train_test_set_from_mat.py", line 87, in <genexpr>
>     scenes = [u''.join(chr(c) for c in h5_file[obj_ref]) for obj_ref in h5_file['sceneTypes'][0]]
> TypeError: only integer scalar arrays can be converted to a scalar index
> ```
> 
> After debugging, I realized that following line was the culprit
> 
> `scenes = [u''.join(chr(c) for c in h5_file[obj_ref]) for obj_ref in h5_file['sceneTypes'][0]]`
> 
> The issue was variable `c` was actually an array of single item and hence the above error. To solve it I replaced the line with `scenes = [u''.join(chr(c[0]) for c in h5_file[obj_ref]) for obj_ref in h5_file['sceneTypes'][0]]`
> 
> Things worked out after that, I checked if images generated looked ok, which they did.
> 
> **I just wanted to confirm if doing this was ok**

Nice, brother!

**Comment by xuelimin** [comment]
邮件已查收，我会尽快回复您！

**Comment by Lost-little-dinosaur** [comment]
Thank you bro! It works!

**Comment by xuelimin** [comment]
邮件已查收，我会尽快回复您！
