### ISSUE TITLE
can't download the  DenseNet-161 model pretrained with ImageNet?

### ISSUE THREAD

**Issue by JokerJohn** [cogaplex-bts/bts#9]
hi, thanks for your work!But I have some problems when I download the zip, use your script download_from_gdrive.py。the error is that:

 python download_from_gdrive.py 1rn7xBF5eSISFKL2bIa8o3d8dNnsrlWfJ models/densenet161_imagenet.zip
Traceback (most recent call last):
  File "C:\Users\catalina\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "C:\Users\catalina\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\connection.py", line 80, in create_connection
    raise err
  File "C:\Users\catalina\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\connection.py", line 70, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] ▒▒▒▒▒▒▒ӷ▒▒▒һ▒▒ʱ▒▒▒û▒▒▒▒ȷ▒𸴻▒▒▒▒ӵ▒▒▒▒▒û▒з▒Ӧ▒▒▒▒▒ӳ▒▒▒ʧ▒ܡ▒

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\catalina\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "C:\Users\catalina\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 344, in _make_request
    self._validate_conn(conn)
  File "C:\Users\catalina\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 843, in _validate_conn
    conn.connect()
  File "C:\Users\catalina\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 316, in connect
    conn = self._new_conn()
  File "C:\Users\catalina\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x0000020B95FCFEC8>: Failed to establish a new connection: [WinError 10060] ▒▒▒▒▒▒▒ӷ▒▒▒һ▒▒ʱ▒▒▒û▒▒▒▒ȷ▒𸴻▒▒▒▒ӵ▒▒▒▒▒û▒з▒Ӧ▒▒▒▒▒ӳ▒▒▒ʧ▒ܡ▒

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\catalina\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\catalina\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\catalina\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=1rn7xBF5eSISFKL2bIa8o3d8dNnsrlWfJ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000020B95FCFEC8>: Failed to establish a new connection: [WinError 10060] ▒▒▒▒▒▒▒ӷ▒▒▒һ▒▒ʱ▒▒▒û▒▒▒▒ȷ▒𸴻▒▒▒▒ӵ▒▒▒▒▒û▒з▒Ӧ▒▒▒▒▒ӳ▒▒▒ʧ▒ܡ▒'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "download_from_gdrive.py", line 43, in <module>
    download_file_from_google_drive(file_id, destination)
  File "download_from_gdrive.py", line 24, in download_file_from_google_drive
    response = session.get(URL, params = { 'id' : id }, stream = True)
  File "C:\Users\catalina\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\catalina\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\catalina\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\catalina\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=1rn7xBF5eSISFKL2bIa8o3d8dNnsrlWfJ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000020B95FCFEC8>: Failed to establish a new connection: [WinError 10060] ▒▒▒▒▒▒▒ӷ▒▒▒һ▒▒ʱ▒▒▒û▒▒▒▒ȷ▒𸴻▒▒▒▒ӵ▒▒▒▒▒û▒з▒Ӧ▒▒▒▒▒ӳ▒▒▒ʧ▒ܡ▒'))

**Comment by cogaplex-bts** [comment]
Hello, there was a mistake in the sharing settings and now it has been fixed.
Could you try again?

**Comment by cogaplex-bts** [comment]
Closing this issue due to inactivity

**Comment by JokerJohn** [comment]
thanks,I have solved it
